#!/bin/bash
# experiment:24_exp_sGuard_rl

dataset_name_exp_sGuard="sGuard_selected"
contract_info_csv_name_prefix="sGuard_contracts_contrarct_info"
contract_group_name_prefix="sGuard_contracts"

group_start_index=1
group_end_index=120


export dataset_name_exp_sGuard contract_info_csv_name_prefix contract_group_name_prefix group_start_index group_end_index



cli_timeout=1000
tool_timeout=900
solver_timeout=10000
execution_times=3
export cli_timeout tool_timeout solver_timeout execution_times



container_run_script_mythril="run_mythril_v0.23.22_for_a_group.sh"
container_run_script_smartExecutor="run_smartExecutor_v3.0_for_a_group.sh"
container_run_script_policySym="run_policySym_for_a_group.sh"

export container_run_script_mythril container_run_script_smartExecutor  container_run_script_policySym

